### ISSUE TITLE
Very useful library, it can store an array of objects also? 

### ISSUE THREAD

**Issue by mohamadir** [AliAsadi/PowerPreference#1]

**Comment by AliTunity** [comment]
Yes, it can.

Example:

ArrayList<Person> arrayList = new ArrayList<>();
arrayList.add(new Person("Ali"));

// PUT
PowerPreference.defult().put("key",arrayList)

//GET
ArrayList<Person> arrayList = PowerPreference.defult().getObject("key",Person[].class)

**Comment by AliAsadi** [comment]
Yes, it can.

Example:

```java
ArrayList<Person> arrayList = new ArrayList<>();
arrayList.add(new Person("Ali"));
```

// PUT

```java
PowerPreference.defult().put("key",arrayList)
```

//GET
```java
ArrayList<Person> arrayList = PowerPreference.defult().getObject("key",Person[].class)
```
