### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by prakaz** [AliAsadi/PowerPreference#2]
When I add `implementation 'com.aliassadi:power-preference-lib:1.3.0'` to the dependencies I get this (suggestive) error:

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.0.0, 25.0.0. Examples include com.android.support:animated-vector-drawable:27.0.0 and com.android.support:recyclerview-v7:25.0.0

Here's my build.gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.prakaz.databinding"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dataBinding{
        enabled = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.aliassadi:power-preference-lib:1.3.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    //Other dependencies... for LiveData, ViewModel
    def lifecycle_version = "1.1.1"
    implementation "android.arch.lifecycle:extensions:$lifecycle_version"
    annotationProcessor "android.arch.lifecycle:compiler:$lifecycle_version"
    testImplementation "android.arch.core:core-testing:$lifecycle_version"
}
```

I'm an Android newbie, so not sure what's happening here.

**Comment by AliTunity** [comment]
Hey Prakaz,

By default the library use ``appcompat-v7`` and ``recyclerview`` version ``25.0.0``

In your app gradle you have implement ``appcompat-v7`` version ``27.0.0``

This is actally how your gradle looks like after implement the ``power-preference-lib`` 

```gradle
implementation 'com.android.support:appcompat-v7:27.0.0'
implementation 'com.android.support:recyclerview-v7:25.0.0'
```

That's mean now you have 2 different version ``25.0.0`` and ``27.0.0`` and the suggestion says:
``All com.android.support libraries must use the exact same version specification``

All you should do is to add the recycler view to your dependices with the same version of the app-compat that you already use and the suggestive should disappear.

### Solution:
```gradle
implementation 'com.android.support:appcompat-v7:27.0.0'
implementation 'com.android.support:recyclerview-v7:27.0.0'
implementation 'com.aliassadi:power-preference-lib:1.3.0'
```

**Comment by AliAsadi** [comment]
Hey Prakaz,

By default the library use ``appcompat-v7`` and ``recyclerview`` version ``25.0.0``

In your app gradle you have implement ``appcompat-v7`` version ``27.0.0``

This is actally how your gradle looks like after implement the ``power-preference-lib`` 

```gradle
implementation 'com.android.support:appcompat-v7:27.0.0'
implementation 'com.android.support:recyclerview-v7:25.0.0'
```

That's mean now you have 2 different version ``25.0.0`` and ``27.0.0`` and the suggestion says:
``All com.android.support libraries must use the exact same version specification``

All you should do is to add the recycler view to your dependices with the same version of the app-compat that you already use and the suggestive should disappear.

### Solution:
```gradle
implementation 'com.android.support:appcompat-v7:27.0.0'
implementation 'com.android.support:recyclerview-v7:27.0.0'
implementation 'com.aliassadi:power-preference-lib:1.3.0'
```

**Comment by prakaz** [comment]
Hey Ali, 

Thanks so much for the explanation! I implemented your solution and it worked! :)

I did notice `implementation 'com.android.support:recyclerview-v7:25.0.0'` when checking the dependencies tree but did not know what it meant and how to fix it. 

Thanks again!
