### ISSUE TITLE
Power Preferences key value pair get deleted after retrieving

### ISSUE THREAD

**Issue by CleatonPais** [AliAsadi/PowerPreference#27]
I am been using Power Preferences and it is great and works perfectly but recently I have added another key-value pair it acts strange

I am able to store the key-value pair and able to retrieve it only once after that it gets deleted

I have narrowed it down getting deleted on the retrieve as it shows the same result on both Android studio device file explorer and PowerPreference.showDebugScreen();

code for setting the power preferences
`
String deviceDBID = data.getDevicedbid();
PowerPreference.getFileByName(powerPrefFile).putString(powerPrefDeviceDBID, deviceDBID);
`

code for retrieving the power preferences
`
String deviceID = PowerPreference.getFileByName(powerPrefFile).getString(powerPrefDeviceDBID);
`

Also posted this on StackOverflow for reference
https://stackoverflow.com/questions/60734816/shared-preferences-removing-data-after-one-time-use

**Comment by AliAsadi** [comment]
I'm not sure I fully understand the issue, you cannot retrieve the data?

**Comment by CleatonPais** [comment]
Thanks for the fast reply
I can retrieve the data but it's only there for one time  the second time it's not there

**Comment by AliAsadi** [comment]
How I can reproduce it?

**Comment by CleatonPais** [comment]
1) this is the data that is stored power pref
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="mapping">{&quot;9&quot;:&quot;104,105&quot;,&quot;10&quot;:&quot;106,107&quot;,&quot;11&quot;:&quot;107,108&quot;}</string>
    <string name="material">{&quot;9&quot;:&quot;ORE&quot;,&quot;10&quot;:&quot;LUMP&quot;,&quot;11&quot;:&quot;FINES&quot;}</string>
    <string name="apiurl">http://test.aniruddhagps.com/iok/mobileapi/</string>
    <string name="destination">{&quot;104&quot;:&quot;A0&quot;,&quot;105&quot;:&quot;A3&quot;,&quot;106&quot;:&quot;A4&quot;,&quot;107&quot;:&quot;A5&quot;,&quot;108&quot;:&quot;A06&quot;,&quot;110&quot;:&quot;A9&quot;}</string>
    <string name="deviceuuid">2ac4114e-4250-488a-84f3-e6c873abfada</string>
</map>


2) add another simple key value pair data eg dbid
`
PowerPreference.getFileByName(powerPrefFile).putString(powerPrefDeviceDBID, deviceDBID);
`

3) check if dbid exist and retrieve else get uuid (also in power pref)
` 
String deviceID ="";
boolean isUUID;
if(PowerPreference.getFileByName(powerPrefFile).contains(powerPrefDeviceDBID)){
	deviceID = PowerPreference.getFileByName(powerPrefFile).getString(powerPrefDeviceDBID, "00");
	isUUID = false;
	System.out.println("isUUID:"+isUUID+", deviceID:"+deviceID);
} else {
	deviceID = deviceUUID;
	isUUID = true;
	System.out.println("isUUID:"+isUUID+", UUID:"+deviceID);
}
`

**Comment by CleatonPais** [comment]
@AliAsadi Were you able to replicate the issue

**Comment by AliAsadi** [comment]
Please provide simple steps.
1. Save
2. Retrieve 

With the values that you are using.
