### ISSUE TITLE
Artifact distribution through JCenter

### ISSUE THREAD

**Issue by dnno** [AliAsadi/PowerPreference#28]
As JCenter is entering end-of-life, do you plan to switch artifact distribution to another repository? I know JCenter will be around in read-only mode, but we'd like to get rid of it from our project, if possible.

**Comment by AliAsadi** [comment]
Hello there, Thank you for reporting and bringing this issue to my attention.
From now on, we'll use the jitpack repository.

**Comment by dnno** [comment]
I'm trying to migrate our project to the jitpack dependency version and removing jcenter as an artefact repository, but I get an error. PowerPreference pulls in a dependency "com.thoughtbot:expandablerecyclerview:1.3", if jcenter is removed it cannot be found. maven central only has a 1.0 version available later versions only exist in proprietary repositories (like spring or mulesoft). Do you have a suggesion how to address this without using jcenter?
