### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by mustafadakhel** [AliAsadi/PowerPreference#3]
Hello..
How can I set the context when getting a value?
OR
How do i use it inside a service?

**Comment by AliAsadi** [comment]
Hey Mustafa,
There is no need to pass a context when you want to get the value.

## Example of using in service

### Save Data
```java
PowerPreference.defult().putString("key",value);
```

### Get Data
```java
PowerPreference.defult().getString("key");
```

**Comment by mustafadakhel** [comment]
Thats exactly how I'm using it but im getting the error "context == null" when i use it inside a service which doesn't happen when i use the original shared preferences method which requires a context

**Comment by AliAsadi** [comment]
It should not be happen, but if you face this issue you can pass the context this way.

```java
public class App extends Application {
    @Override
    public void onCreate() {
     PowerPreference.setSingletonInstance(new PowerPreference.Builder(this).build());
    }
}
```

Update your library to last version:
```gradle
implementation 'com.aliassadi:power-preference-lib:1.3.1'
```
Let me know if this resolves your issue :)
