### ISSUE TITLE
Saving List

### ISSUE THREAD

**Issue by prakaz** [AliAsadi/PowerPreference#4]
Hi Ali, is it possible to save a list of values? 

I noticed the Android Studio's Settings Activity template saves `MultiSelectListPreference` data as follows:

```
<map>
    <set name="list">
        <string>sat</string>
        <string>sun</string>
    </set>
</map>
```

What is the best way to save this kind of list with Powerpreference? 

Thanks!

**Comment by AliAsadi** [comment]
Hey, this is the best way to store and retrieve list using power preference.

### Example
```java
ArrayList<String> list = new ArrayList<>();
list.add("sat");
list.add("sun");
```

### PUT

```java
PowerPreference.defult().put("key",list)
```

### GET
```java
ArrayList<String> list = PowerPreference.defult().getObject("key",String[].class)
```

**Comment by prakaz** [comment]
Looks good. Thanks!

Would be nice if you updated this in the documentation.

**Comment by AliAsadi** [comment]
Updated, Thanks!
