### ISSUE TITLE
Feedback～

### ISSUE THREAD

**Issue by Omooo** [AliAsadi/PowerPreference#8]
Hello author, read your code, it is really great for SP packaging~
But unfortunately, every time "edit" is to open a file, each time "apply" is full-write, which is actually the reason for poor SP performance.
Recently, I also want to write an efficient "key-value" component, so I saw your code, welcome to exchange ~

作者你好，看了你的代码，对于 SP 封装的的确很棒～
但是可惜的是，每次 “edit” 都是打开一次文件，每次 “apply” 都是全量写入，这其实也是 SP 性能差的原因所在。
最近，我也想写一个高效的 "key-value" 组件，所以看到了你的代码，欢迎交流～

**Comment by AliAsadi** [comment]
Hey Omooo, Thank you for the feedback. 

The library comes to simplify the usage of shared preference at the first class, about the performance you are right we can improve how it works, I believe in open source and looking forward to your contributions so we can make it works better.
